SLOTS_PER_HOUR = 4
BLOCK_HOURS = 2
BLOCK_SLOTS = BLOCK_HOURS * SLOTS_PER_HOUR
SLOTS_PER_DAY = 24 * SLOTS_PER_HOUR

RA_WEEK_MAX = 9
RA_PP_MAX = 18
NONCA_WEEK_MAX = 15
NONCA_PP_MAX = 30
ALL_WEEK_MIN = 3
ALL_PP_MIN = 6
DAILY_SOFT_MAX = 4
DAILY_HARD_MAX = 6
